version: "3"
services:
  web:
    image: tutum/apache-php
    environment:
      - ALLOW_OVERRIDE=true
    volumes:
      - ./app/app
    ports:
      - "80:80"
    networks:
      - overlay
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        
  mysql:
    image: mariadb
    volumes:
       - ./mysql:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: admin
       MYSQL_PASSWORD: test
       MYSQL_DATABASE: penjualan
    ports:
       - "8889:3306"
    networks:
       - overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  overlay:
